(require 'package)
(add-to-list 'package-archives
                          '("marmalade" . "http://marmalade-repo.org/packages/") t)
(package-initialize)

(when (not package-archive-contents)
  (package-refresh-contents))

;; Add in your own as you wish:
(defvar my-packages '(starter-kit starter-kit-ruby starter-kit-bindings starter-kit-js
                                  scss-mode
                                  color-theme
                                  color-theme-sanityinc-tomorrow
                                  color-theme-solarized
                                  zencoding-mode 
                                  markdown-mode
                                  rvm
                                  )
  "A list of packages to ensure are installed at launch.")

(dolist (p my-packages)
  (when (not (package-installed-p p))
    (package-install p)))

;; keep buffers from last session
(desktop-save-mode 1)

;; Frame managements: resizing 'windows' (i.e., inside the frame) // flicked from http://goo.gl/V8ZVM
(global-set-key (kbd "S-C-<left>") 'shrink-window-horizontally)
(global-set-key (kbd "S-C-<right>") 'enlarge-window-horizontally)
(global-set-key (kbd "S-C-<down>") 'shrink-window)
(global-set-key (kbd "S-C-<up>") 'enlarge-window)

;; quick eval-buffer
(global-set-key (kbd "S-C-<return>") 'eval-buffer)

;; hack for html5 tags to zencoding
(defun add-html5-tags ()
  "Adds a few html5 tags to zencoding-mode"
  (defvar zencoding-inline-tags 
    (append zencoding-inline-tags 
          '( "header" "nav" "section" "article" "aside" "footer" ))))

(add-hook 'sgml-mode-hook 'zencoding-mode) ;; Auto-start on any markup modes
(add-hook 'zencoding-mode-hook 'add-html5-tags)

;; font
(set-frame-font "Menlo-12")

;; take ruby from rvm
(rvm-use-default)

;; make compass imports available
;; (setq scss-sass-options '("--compass" "-r susy"))
;; 
;; ^ since this isn't generic enough, I'd like to keep a compass watch
;; running elsewhere, scss-mode is quite good for scss+compass-only
;; projects then.

;; actually I just need to disable auto compilation
(setq scss-compile-at-save nil)

;; allow undo on layout/frame/window changes
(winner-mode)

;; misc third-party styff
(add-to-list 'load-path (concat "~/.emacs.d/misc"))

(autoload 'save-current-configuration "revive" "Save status" t)
(autoload 'resume "revive" "Resume Emacs" t)
(autoload 'wipe "revive" "Wipe Emacs" t)

;; bindings for doing it manually
(define-key ctl-x-map "S" 'save-current-configuration)
(define-key ctl-x-map "F" 'resume)
(define-key ctl-x-map "K" 'wipe)

;; lets get some sublime text 2 pleasures back
;; save config before quitting
(add-hook 'kill-emacs-hook 'save-current-configuration)
;; restore config once up
(resume)
;; WARN - always save config before evaling init.el

;; delete complete line
(global-set-key (kbd "C-k") 'kill-whole-line)

;; Customize-theme autogenerated stuff
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(background-color "#042028")
 '(background-mode dark)
 '(cursor-color "#708183")
 '(custom-enabled-themes (quote (sanityinc-tomorrow-night)))
 '(custom-safe-themes (quote ("1e7e097ec8cb1f8c3a912d7e1e0331caeed49fef6cff220be63bd2a6ba4cc365" "628278136f88aa1a151bb2d6c8a86bf2b7631fbea5f0f76cba2a0079cd910f7d" "bb08c73af94ee74453c90422485b29e5643b73b05e8de029a6909af6a3fb3f58" "1b8d67b43ff1723960eb5e0cba512a2c7a2ad544ddb2533a90101fd1852b426e" "4cf3221feff536e2b3385209e9b9dc4c2e0818a69a1cdb4b522756bcdf4e00a4" "30fe7e72186c728bd7c3e1b8d67bc10b846119c45a0f35c972ed427c45bacc19" "21d9280256d9d3cf79cbcf62c3e7f3f243209e6251b215aede5026e0c5ad853f" "fc5fcb6f1f1c1bc01305694c59a1a861b008c534cae8d0e48e4d5e81ad718bc6" "06f0b439b62164c6f8f84fdda32b62fb50b6d00e8b01c2208e55543a6337433a" "82d2cac368ccdec2fcc7573f24c3f79654b78bf133096f9b40c20d97ec1d8016" "4aee8551b53a43a883cb0b7f3255d6859d766b6c5e14bcb01bed572fcbef4328" default)))
 '(foreground-color "#708183"))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )



;; a bit darker, to ditto match our tomorrow-night theme in sublime text 2
(set-face-background 'default "#161718")
